
// auth
export const LOGIN = 'LOGIN';
export const REGISTRATION = 'REGISTRATION';
export const FORGOT_PASS_REQUEST = 'FORGOT_PASS_REQUEST';
export const FORGOT_PASS_OTP = 'FORGOT_PASS_OTP';
export const GET_EMAIL_MOBILE = 'GET_EMAIL_MOBILE';
export const FORGOT_PASS_RESET = 'FORGOT_PASS_RESET';
export const FORGOT_PASS_DATA = 'FORGOT_PASS_DATA';
export const USER_EMAIL_VERIFY_SEND = 'USER_EMAIL_VERIFY_SEND';
export const USER_EMAIL_VERIFY_PROCESS = 'USER_EMAIL_VERIFY_PROCESS';
export const USER_MOBILE_VERIFY_PROCESS = 'USER_MOBILE_VERIFY_PROCESS';
export const USER_MOBILE_VERIFY_SEND = 'USER_MOBILE_VERIFY_SEND';
export const VERIFY_OTP = 'VERIFY_OTP';
// user
export const USER_PROFILE_DETAILS = 'USER_PROFILE_DETAILS';
export const USER_PROFILE_DETAILSBYID = 'USER_PROFILE_DETAILSBYID';
export const USER_CHANGE_PASSWORD = 'USER_CHANGE_PASSWORD';
export const USER_UPDATE_PROFILE = 'USER_UPDATE_PROFILE';
export const UPDATE_PROFILE_IMAGE = 'UPDATE_PROFILE_IMAGE';
export const UPDATE_PROFILE_IMAGE_COVER = 'UPDATE_PROFILE_IMAGE_COVER';
export const GET_ALL_USER_CARDS = 'GET_ALL_USER_CARDS';
export const CREATE_USER_CARDS = 'CREATE_USER_CARDS';
export const UPDATE_USER_CARDS = 'UPDATE_USER_CARDS';
export const DELETE_USER_CARDS = 'DELETE_USER_CARDS';
export const GET_ALL_USER_BILLING_INFO = 'GET_ALL_USER_BILLING_INFO';
export const GET_USER_LICENSE = 'GET_USER_LICENSE';
export const GET_USER_WALLET = 'GET_USER_WALLET';
export const LOGIN_HISTORY = 'LOGIN_HISTORY';
export const HISTORY_LOGOUT = 'HISTORY_LOGOUT';
export const LIST_PROPERTY = 'LIST_PROPERTY';
export const DELETE_PROPERTY = 'DELETE_PROPERTY';
export const GET_ALL_PROPERTY = 'GET_ALL_PROPERTY';
export const BOOK_PROPERTY_PARAMETER = 'BOOK_PROPERTY_PARAMETER';
export const GET_PROPERTY = 'GET_PROPERTY';
export const GET_PROPERTY_BY_PROPERTY_ID = 'GET_PROPERTY_BY_PROPERTY_ID';
export const UPDATE_PROPERTY = 'UPDATE_PROPERTY';
export const GET_PROPERTY_BY_USERID = 'GET_PROPERTY_BY_USERID';
export const ADD_CARD = 'ADD_CARD';
export const GET_CARD = 'GET_CARD';
export const DELETE_CARD = 'DELETE_CARD';
export const GET_USER_NOTIFICATION = 'GET_USER_NOTIFICATION';
export const SET_NOTIFICATION_SETTING = 'SET_NOTIFICATION_SETTING';
export const GET_ALL_FILTERED_PROPERTY = 'GET_ALL_FILTERED_PROPERTY';
export const CREATE_PROPERTY_BOOKING = 'CREATE_PROPERTY_BOOKING';
export const CANCEL_PROPERTY_BOOKING = 'CANCEL_PROPERTY_BOOKING';
export const CANCEL_PROPERTY_BOOKING_BY_HOST_USER = 'CANCEL_PROPERTY_BOOKING_BY_HOST_USER';
export const UPDATE_PROPERTY_BOOKING = 'UPDATE_PROPERTY_BOOKING';
export const GET_BOOKING_BY_ID = 'GET_BOOKING_BY_ID';
export const DEACTIVATE_USER = 'DEACTIVATE_USER';
export const OTHER_USER_PROFILE_DETAILS = 'OTHER_USER_PROFILE_DETAILS';
export const ADD_PRODUCT_TO_WISHLIST = 'ADD_PRODUCT_TO_WISHLIST';
export const ADD_PROPERTY_REVIEW = 'ADD_PROPERTY_REVIEW';
export const USER_CHAT_LIST = 'USER_CHAT_LIST';
export const GET_BOOKING_BY_USER_ID = 'GET_BOOKING_BY_USER_ID';
export const CREATE_WISH_LIST = 'CREATE_WISH_LIST';
export const ADD_USER_REVIEW = 'ADD_USER_REVIEW';
export const PROPERTY_ALLOTMENT_GET_DATE = 'PROPERTY_ALLOTMENT_GET_DATE';
export const GET_PROPERTY_BOOKING_LIST_BY_HOST_ID = 'GET_PROPERTY_BOOKING_LIST_BY_HOST_ID';
export const GET_ALL_NOTIFICATON_BY_USERID = 'GET_ALL_NOTIFICATON_BY_USERID';




// common
export const UPLOAD_FILE_DATA = 'UPLOAD_FILE_DATA';
export const SEND_NOTIFICATION = 'SEND_NOTIFICATION';
export const TRANSACTION_LIST = 'TRANSACTION_LIST';
export const CREATE_FIREBASE_TOKEN = 'CREATE_FIREBASE_TOKEN';
export const GET_ACTIVE_TOKEN = 'GET_ACTIVE_TOKEN';

// image Light Box
export const LIGHTBOX_DEFAULT_URL = 'LIGHTBOX_DEFAULT_URL';
export const LIGHTBOX_IMAGES = 'LIGHTBOX_IMAGES';
export const LIGHTBOX_VIEW_STATUS = 'LIGHTBOX_VIEW_STATUS';
export const TRAINING_MODULE = 'TRAINING_MODULE';
export const ASK_AGRONOMIST = 'ASK_AGRONOMIST';
export const PROFILE_UPDATE ='PROFILE_UPDATE';
export const GET_QUERIES ='GET_QUERIES';