const en = {
    Announcement:'ANNOUNCEMENT',
    Training:'TRAINING',
    Weather_update:'WEATHER UPDATE',
    Login:'LOGIN',
    Sign_up:'SIGN UP',
    As_a_member_of_cooperative:'AS A MEMBER OF COOPERATIVE',
    As_an_individual:'AS AN INDIVIDUAL',
    As_a_member_of_cooperative_Small:'As a member of cooperative',
    As_an_individual_Small:'As an individual',
    Mobile:'Mobile',
    Password:'Password',
    Change:'CHANGE',
    Change_password:'CHANGE PASSWORD',
    Confirm_password:'Confirm password',
    Dont_have_an_account:'Don’t have an account',
    Sign_up_here:'Sign up here',
    Welcome:'Welcome',
    Ask_and_agronomist:'ASK AN AGRONOMIST',
    Commodity_market:'COMMODITY MARKET',
    Farm_Records:'FARM RECORD',
    All_items:'All items',
    Recent:'Recent',
    Old:'Old',
    Take_test:'TAKE TEST',
    Question:'Question',
    QuestionD:'Question',
    to:'To',
    Download:'Download',
    Submit:'SUBMIT',
    Result:'Result',
    You_have_completed:'You have Completed',
    out_of:'out of',
    You_score:'You Score',
    Pass:'Pass',
    Fail:'Fail',
    Ask_your_question:'Ask your Question',
    Type_here:'Type here',
    Upload_image:'Upload Image',
    My_questions:'MY QUESTION',
    Other_questions:'Other questions',
    You_have_10_answers:'You have 10 answers',
    Weather:'WEATHER',
    Location:'Location',
    Description:'Description',
    Add_price:'Add Price',
    Upload_image:'Upload Image',
    Date:'Date',
    Add_record:'Add Record',
    Download_file:'DOWNLOAD FILE',
    To:'To',
    From:'From',
    Notifications:'NOTIFICATIONS',
    Today:'Today',
    Previous_notifications:'Previous notifications',
    Profile:'PROFILE',
    Name:'Name',
    Gender:'Gender',
    Mobile:'Mobile Number',
    Email:'Email',
    Settings:'SETTINGS',
    Edit_profile:'Edit Profile',
    Change_password_Small:'Change password',
    Notification:'Notification',
    Regional:'Regional',
    Language:'Language',
    About:'About',
    Logout:'Logout',
    Current_password:'Current Password',
    New_password:'New Password',
    Confirm_password:'Confirm Password',
    Reset_button:'RESET'

}
const sw = {
    Announcement:'Matangazo',
    Training:'Masomo',
    Weather_update:'Hali ya hewa',
    Login:'Ingia',
    Sign_up:'Jisajili',
    As_a_member_of_cooperative:'Kama memba wa kikundi au ushirika',
    As_an_individual:'Mkulima binafsi',
    As_a_member_of_cooperative_Small:'Kama memba wa kikundi au ushirika',
    As_an_individual_Small:'Mkulima binafsi',
    Mobile:'Nambari ya simu',
    Password:'Nenosiri',
    Change:'Badilisha',
    Change_password:'Badilisha neno siri',
    Confirm_password:'Hakikisha neno siri',
    Dont_have_an_account:'Hauna akaunti',
    Sign_up_here:'Jisajili hapa',
    Welcome:'Karibu',
    Ask_and_agronomist:'Uliza mtaalamu',
    Commodity_market:'Soko ya bidhaa',
    Farm_Records:'Rekodi za shamba',
    All_items:'matangazo yote',
    Recent:'Hivi karibuni',
    Old:'Ya zamani',
    Take_test:'Anza zoezi',
    Question:'Swali',
    QuestionD:'',
    to:'hadi',
    Download:'Pakua',
    Submit:'Wasilisha',
    Result:'Matokeo',
    You_have_completed:'Umekamilisha maswali',
    out_of:'kati ya maswali',
    You_score:'Alama yako',
    Pass:'Umefaulu',
    Fail:'Umefeli',
    Ask_your_question:'Uliza swali yako',
    Type_here:'Andika hapa',
    Upload_image:'Pakia picha',
    My_questions:'Maswali yangu',
    Other_questions:'Maswali mengine',
    You_have_10_answers:'Uko na majibu 10',
    Weather:'Hali ya hewa',
    Location:'Eneo',
    Description:'Maelezo',
    Add_price:'Weka bei',
    Upload_image:'Pakia picha',
    Date:'Tarehe',
    Add_record:'Wasilisha rekodi',
    Download_file:'Pakua faili',
    To:'Hadi',
    From:'Kutoka',
    Notifications:'Arifa',
    Today:'Leo',
    Previous_notifications:'Arifa za awali',
    Profile:'Wasifu wa mtumiaji',
    Name:'Jina',
    Gender:'Jinsia',
    Mobile:'Nambari ya simu',
    Email:'Barua pepe',
    Settings:'Mipangilio',
    Edit_profile:'Badilisha wasifu wa mtumiaji',
    Change_password_Small:'Badilisha neno siri',
    Notification:'Arifa',
    Regional:'Eneo',
    Language:'Lugha',
    About:'Kuhusu hii app',
    Logout:'Ondoka',
    Current_password:'Nenosiri la sasa',
    New_password:'Nenosiri mpya',
    Confirm_password:'Hakikisha nenosiri',
    Reset_button:'Wasilisha'


}
export {en,sw}